WIDTH, HEIGHT = 800, 600
TILE_SIZE = 32
PLAYER_RADIUS = 20
PLAYER_SPEED = 2.5
ENEMY_SPEED = 2.5
PLAYER_HEALTH = 100
SCORE = 0
# Gun related shit
EQUIPPED = "none"
BULLET_SPEED = "none"
BULLET_INACCURACY = "none"
AMMO_CAPACITY = "none"
AMMO_COUNT = "none"
RELOAD_TIME = "none"
DAMAGE = "none"
PENETRATION = "none"
GUNSHOT_SOUND = "none"
RELOAD_SOUND = "none"

IS_RELOADING = False

ENEMY_SPAWN_RATE = [3000, 5000]

BOX_REFRESH_SPEED = 5000
BOX_LAST_HIT = 0